services:
  - type: web
    name: city-safari-backend
    env: java
    rootDir: city-safari-backend
    buildCommand: "mvn clean package -DskipTests"
    startCommand: "java -jar target/city-safari-backend-1.0.0.jar"
    envVars:
      - key: JAVA_VERSION
        value: 17
